### ISSUE TITLE
Missing graphics in certain questions

### ISSUE THREAD

**Issue by PetePriority** [deveth0/FuehrerscheinApp#1]
Missing graphics in questions: (list may not be complete)
- 188
- 282
- 162

![screenshot_2015-09-02-10-12-36](https://cloud.githubusercontent.com/assets/8421182/9632430/78d3de4c-5187-11e5-861f-be832adeb19f.png)

**Comment by PetePriority** [comment]
It seems like the big size (in particular the width) is causing this issue.
Maybe a simple rescaling of the affected pngs could resolve this?

**Comment by deveth0** [comment]
good point, thank you very much! I'll have a look at this asap!

**Comment by deveth0** [comment]
Ok, the issue was the following:
Android does not support bitmaps larger than 4096px.
I added a rescaling in d13f32549661bbe93980f285e3ee93bba7068e13

**Comment by deveth0** [comment]
release published to playstore :)
